"use strict";
(function() {
	module.exports = [
		"Skiing Equipment",
		"Deodorant Brand",
		"Lord of the Rings Character",
		"Radio Personality",
		"Phobia",
		"Bad Smell",
		"Foot Part",
		"World Series Winner",
		"Type of Sweater",
		"Gas Station",
		"Noun of Assemblage",
		"Cable TV Channel",
		"Train Station",
		"Form of Exercise",
		"Religious Figure",
		"Shoe Brand",
		"Renewable Energy Source",
		"Cell Phone Brand",
		"Famous Sculpture",
		"Fruit Juice",
		"Animated Movie",
		"Lizard",
		"Nursery Rhyme",
		"Record Label",
		"Wind Instrument",
		"Battery Brand",
		"Poet",
		"Hitchcock Film",
		"Bird of Prey",
		"Songwriting Duo",
		"Sandwich",
		"Insulting Name",
		"Scandinavian City",
		"Dentist's Tool",
		"80's TV Show",
		"Mammal",
		"One Hit Wonder",
		"Canadian City",
		"Meat",
		"Spanish City",
		"Unit of Liquid Measurement",
		"TV News Show",
		"Part of Speech",
		"Political Party",
		"Method of Communication",
		"House Plant",
		"Newscaster",
		"Type of Storm",
		"Cooking Utensil",
		"Basketball Player",
		"Yogurt Brand",
		"Sports Car",
		"Advice Columnist",
		"Famous Criminal",
		"Sushi Fish",
		"Popular Diet",
		"Funny Sound",
		"Middle Eastern Country",
		"Serial Killer",
		"Asian Country",
		"Desert Animal",
		"Dictator",
		"War",
		"Type of Doctor",
		"Apple Variety",
		"Circus Performer",
		"College",
		"Legume",
		"Chess Piece",
		"Soap Opera",
		"Pen Brand",
		"Cough Drop Brand",
		"Country Musician",
		"Middle Eastern City",
		"Type of Rock",
		"Elvis Song",
		"Flightless Bird",
		"Playground Game",
		"Type of Government",
		"Crustacean",
		"Primate",
		"Prime Number",
		"Novel",
		"Brady Bunch Character",
		"Rain Gear",
		"Pianist",
		"Energy Drink",
		"Shade of Green",
		"Watch Brand",
		"Cooking Method",
		"Famous Vehicle",
		"70s TV Show",
		"Football Team",
		"Town",
		"Construction Vehicle",
		"Goddess",
		"Percussion Instrument",
		"Boulevard",
		"South American Country",
		"Comic Book",
		"Spider",
		"Federal Holiday",
		"Asian Religion",
		"Asian City",
		"Carnivorous Animal",
		"Type of Puzzle",
		"Explosion Sound",
		"Cat Food Brand",
		"Science Fiction Author",
		"Type of Crime",
		"Halloween Costume",
		"Secondary Color",
		"First Aid Item",
		"Famous Puppet",
		"Fashion Magazine",
		"Cake Ingredient",
		"TV Mini-Series",
		"Baseball Player",
		"Latin American Author",
		"Potato Chip Flavor",
		"Wonder of the World",
		"Medical Occupation",
		"Hip Hop Artist",
		"Famous Cowboy",
		"County",
		"Atomic Particle",
		"Direction",
		"Actress",
		"Pirate",
		"Harry Potter Book",
		"White Food",
		"Horned Animal",
		"Unit of Energy",
		"Vacation Spot",
		"WWE Wrestler",
		"French City",
		"Sundae Topping",
		"Winter Sport"
	];
})();
